version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run Automated iOS Tests
          command: |
            mvn test-compile \
              -Pss_run \
              -DapiKey=${APPLAUSE_API_KEY} \
              -DdriverId=2301 \
              -Dexecution=serverside \
              -DsuiteFile=testng/mobile/debug.xml \
              -DproductId=20269 \
              -DdownloadResults=never
      - run:
          name: Run Automated Android Tests
          command: |
            mvn test-compile \
              -Pss_run \
              -DapiKey=${APPLAUSE_API_KEY} \
              -DdriverId=2252 \
              -Dexecution=serverside \
              -DsuiteFile=testng/mobile/debug.xml \
              -DproductId=20270 \
              -DdownloadResults=never
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: v2-conversion