version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run Automated Tests
          command: |
            mvn test-compile -P ss-run \
              -DapiKey=${APPLAUSE_API_KEY} \
              -DdriverId=1304 \
              -Dexecution=serverside \
              -DsuiteFile=testng/web/login.xml \
              -DproductId=19830 \
              -DdownloadResults=always \
              -DsetupCommand='bash ./setup/setup_sc.sh -v4.5.3 -upeetscoffee-auto -k${SC_API_KEY} -hproxy.utest.com:9999 -cutest:${APPLAUSE_PROXY_PASSWORD} -tsc.peetscoffee-auto'
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: v2-conversion