version: 2.1
orbs:
  sumologic: circleci/sumologic@1.0.4
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run Automated iOS Tests
          command: |
            mvn clean compile test \
              -DapiKey=${APPLAUSE_API_KEY} \
              -DdriverId=2301 \
              -Dexecution=clientside \
              -DsuiteFile=testng/mobile/debug.xml \
              -DproductId=20269 \
              -DtestRetryCount=0 \
              -DdownloadResults=never
workflows:
  test:
    jobs:
      - sumologic/workflow-collector
      - test:
          filters:
            branches:
              only: v2-conversion